server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes:
        - id: shop_route
          uri: lb://shop # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/shop/**
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**
#         权限系统网关
#        - id: auth_gateway_route
#          uri: lb://auth-gateway-lwx
#          predicates:
#            - Path=/auth-mananger-microservice-lwx, /api/external/**
#        - id: auth-mananger-microservice-lwx
#          uri: lb://auth-mananger-microservice-lwx
#          predicates:
#            - Path=/auth-mananger-microservice-lwx
##            - Path=/api/auth-manager/**
#            #          filters:
#            #            - StripPrefix=1
#        - id: auth-external-microservice-lwx
#          uri: lb://auth-external-microservice-lwx
#          predicates:
#            - Path=/api/external/**
#          filters:
#            - StripPrefix=1


