# web port
server:
  port: 8081
# no web
#spring.main.web-environment=false

# log config
logging:
  config:
    classpath: logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin

### xxl-job, access token
    accessToken: default_token

### xxl-job executor appname
    executor:
      appname: xxl-job-executor-sample
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
### xxl-job executor server-info
      ip:
      port: 9999
### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
      logretentiondays: 30



spring:
  application:
    name: shop
  cloud:
    nacos:
      discovery:
        #        server-addr: 43.138.149.121:8848
        server-addr: 127.0.0.1:8848
        locator:
          lower-case-service-id: true
        register-enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: lwxMysql
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500

mybatis:
  type-aliases-package: org.example.domain   #  ?????????????
  mapper-locations: classpath:mappers/*.xml #  ???mapper????

# mybatis-plus????
mybatis-plus:
  # xml??????????????????? Mapper ???? XML ?????
  mapper-locations: classpath:mappers/*.xml
  # ?????????,?????
  global-config:
    db-config:
      #???? AUTO:"???ID??" INPUT:"????ID",ID_WORKER:"????ID (??????ID)", UUID:"????ID UUID";
      id-type: auto
      #???? IGNORED:"????"  NOT_NULL:"? NULL ??")  NOT_EMPTY:"????"
      field-strategy: NOT_EMPTY
      #?????
      db-type: MYSQL
  configuration:
    # ??????????????:???????Java???????????
    map-underscore-to-camel-case: true
    # ??????????????? MyBatis ???????????????
    call-setters-on-nulls: true
    # ?????????sql?????????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
